Replaced Game Titles with their Icon
AsoDesu/IslandUtils pull request #150
Opened 2024-09-10 20:17 UTC by HenriTom

Replaced the game icons with their icon resolving #148 
Added an option for that in the Misc tab

2024-10-06 14:38 UTC, AsoDesu requested changes
this isn't really the effect that we're going for,

what we are trying to do is replicate the game titles at the start of games in MCC ([see this clip as an example, with the parkour warrior title](https://youtube.com/clip/Ugkxyy6hPC77UkMl9clZDyUCfmTvQnbGjoQk?si=wGWBnO5G7infGUhQ))

the icons displayed are too small, and need to be faded in and out properly
also please do not forcibly hide and unhide the players ui, it can and will get really annoying


my suggestion is instead of rendering the icons yourself, load in the game titles in a font, and then show them as a title (which is exactly what MCC does in the event)
you also may have to use a mixin to remove the current title which displays when you enter a game:

https://github.com/user-attachments/assets/78b0aaec-0902-4a30-98d9-0390f9cec41d

2024-10-06 14:38 UTC, AsoDesu commented on src/main/java/net/asodev/islandutils/util/IngameIcons.java
> +                    MC.options.hideGui = false;
please don't ever forcibly hide or unhide the player's gui.

2024-10-06 14:38 UTC, AsoDesu commented on src/main/java/net/asodev/islandutils/util/IngameIcons.java
> +public class IngameIcons {
this should be named `InGameIcons`

2024-10-06 14:38 UTC, AsoDesu commented on src/main/java/net/asodev/islandutils/util/IngameIcons.java
> +            MC.options.hideGui = true;
do not hide gui every frame.

2024-10-07 15:38 UTC, UltraTeal commented
So the logos aren’t the correct ones they are the old island icons the new ones are in the drive I sent tho the dynaball one is right

2024-12-26 03:12 UTC, closed without merging